# Generated by Django 4.0.2 on 2022-02-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_documents_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='file',
        ),
    ]
